import About from '@/components/About'
import Banner from '@/components/Banner'
import Contacts from '@/components/Contact'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Projects from '@/components/Projects'
import Services from '@/components/Services'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>United Development Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className='w-full h-screen font-bodyFont text-secondary'>
      <Navbar />
    <div>
    <Banner />
   <About />
   <Services />
   <Projects />
   <Contacts />
   <Footer />
    </div>
     
    
      
    </main>
    
    </>
  )
}
